### ISSUE TITLE
range versions doesn't work

### ISSUE THREAD

**Issue by octavioroncal** [jcabi/jcabi-aether#103]
Is there support to range versions?
When I try to resolve an artifact with range version, aether throws an IllegalArgumentException.
`java.lang.IllegalArgumentException: Bad artifact coordinates io.intino.konos:alexandria-core:[1.0.0, 2.0.0), expected format is <groupId>:<artifactId>[:<extension>[:<classifier>]]:<version>`

is there any way to resolve that? Will you support them?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@octavioroncal[/z](https://www.0crat.com/u/octavioroncal) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by octavioroncal** [comment]
Solved: Just use another constructor of DefaultArtifact

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-aether#103` is not assigned, can't get performer
