### ISSUE TITLE
 Aether doesn't read proxy information from maven

### ISSUE THREAD

**Issue by krzyk** [jcabi/jcabi-aether#11]
Aether should read proxy information from maven settings.xml file.

**Comment by dmarkov** [comment]
@darkled just a reminder that you're working with this task for 12 days already... -30 added to your rating, current score is: [+90](http://www.netbout.com/b/35091?open=rating)

**Comment by darkled** [comment]
@dmarkov please, assign this task to someone else

**Comment by dmarkov** [comment]
> @dmarkov please, assign this task to someone else

@darkled no problem, I'll try to find somebody else

**Comment by dmarkov** [comment]
@darkled the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html)... -60 to your rating, your total score is [-135](http://www.netbout.com/b/35091?open=rating)

**Comment by darkled** [comment]
@dmarkov @yegor256 I am not sure these -60 are correct, since I've rejected the task 3 days ago, aren't they?

**Comment by dmarkov** [comment]
@aoxa this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here... The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by aoxa** [comment]
Could you please provide more information as to how to reproduce this? I'm still new to the project and will need more data to solve some issue, but will try to get up to speed asap.

**Comment by dmarkov** [comment]
@aoxa the task is your hands for the last 15 days.. keep in mind that if it's not closed in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... added -30 to your rating, now it is equal to -240

**Comment by aoxa** [comment]
HI @dmarkov I'm unable to build aether, it states that there are some tests failing even when I ran with -DskipTests. I have a possible solution but am unable to verify if it runs.
I've forked, updated the fork version, but still fails.

**Comment by aoxa** [comment]
Tests in error: 
  ClasspathTest.returnsArtifactWithHighestVersionNumber:102 » IllegalState class...
  ClasspathTest.buildsClasspath:72 » IllegalState class com.jcabi.aether.Aether ...
  ClasspathTest.comparesToAnotherClasspath:187 » IllegalState class com.jcabi.ae...
  ClasspathTest.buildsClasspathWithoutOptionalArtifacts:140 » IllegalState class...
  ClasspathTest.hasToStringWithBrokenDependency:165 » IllegalState class com.jca...
  RootArtifactTest.gracefullyResolvesBrokenRootArtifact:94->aether:123 » IllegalState
  RootArtifactTest.resolvesRootArtifact:69->aether:123 » IllegalState class com....
  AetherTest.resolvesArtifactsInParallelThreads:133 » IllegalState class com.jca...
  AetherTest.throwsWhenArtifactNotFound »  Unexpected exception, expected<org.so...
  AetherTest.rejectsNullArtifact »  Unexpected exception, expected<javax.validat...
  AetherTest.recoversAfterFailure:225 » IllegalState class com.jcabi.aether.Aeth...
  AetherTest.findsAndLoadsArtifacts:95 » IllegalState class com.jcabi.aether.Aet...
  AetherTest.rejectsNullScope »  Unexpected exception, expected<javax.validation...

Tests run: 20, Failures: 0, Errors: 13, Skipped: 0
That is via maven

**Comment by yegor256** [comment]
@aoxa if master is broken, submit a bug about it, see http://www.yegor256.com/2014/04/13/bugs-are-welcome.html

**Comment by dmarkov** [comment]
@aoxa the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html)... -60 added to your rating, current score is: -450

**Comment by dmarkov** [comment]
@adko-pl the task is yours, go ahead

**Comment by adko-pl** [comment]
@dmarkov changes delivered in https://github.com/jcabi/jcabi-aether/pull/55

**Comment by adko-pl** [comment]
@dmarkov changes have been merged, please close this ticket

**Comment by pinaf** [comment]
@adko-pl you should ask the creator of the issue @krzyk to close it.

**Comment by krzyk** [comment]
thanks

**Comment by dmarkov** [comment]
once `11-2b91e5db` puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by dmarkov** [comment]
@adko-pl I just added **31 mins** to your account, many thanks for your contribution..

added +31 to your rating, now it is equal to [+76](http://www.netbout.com/b/35150?open=rating)
