### ISSUE TITLE
pom.xml:267-267: This test fails with Maven...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aether#21]
Puzzle `18-d2cf5a94` in `pom.xml:267-267` has to be resolved: This test fails with Maven 3.2.x -->

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@jenya it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -60 to your rating, your total score is [-315](http://www.netbout.com/b/35092?open=rating)

**Comment by dmarkov** [comment]
@pinaf This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by pinaf** [comment]
@dmarkov @yegor256 Not sure there is anything to be done here.

Uncommented line 267 in `pom.xml`
```xml
<pomInclude>aether-test/pom.xml</pomInclude>
```
and ran `mvn clean install -Pqulice` getting
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:26 min
[INFO] Finished at: 2015-01-20T00:14:45-03:00
[INFO] Final Memory: 98M/416M
[INFO] ------------------------------------------------------------------------
```

Here is the output of `mvn --version`
```
$ mvn --version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T15:37:52-03:00)
Maven home: /usr/share/maven3
Java version: 1.7.0_65, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-24-generic", arch: "amd64", family: "unix"
```

Maybe the error is more subtle?

**Comment by yegor256** [comment]
@pinaf sometimes issues are easily resolved. Just remove the comment and the puzzle and send a pull request

**Comment by pinaf** [comment]
@dmarkov please see PR #50

**Comment by pinaf** [comment]
@dmarkov merged, please close.

**Comment by pinaf** [comment]
@dmarkov fixed and deployed :)

**Comment by pinaf** [comment]
@dmarkov ping

**Comment by dmarkov** [comment]
Closing..

**Comment by dmarkov** [comment]
@pinaf I just added **30 mins** to your account, many thanks for your contribution..

added +30 to your rating, now it is equal to [+180](http://www.netbout.com/b/35128?open=rating)

**Comment by pinaf** [comment]
@dmarkov thank you
