### ISSUE TITLE
'outside of Maven infrastructure' sample does not build in Eclips

### ISSUE THREAD

**Issue by quartelh** [jcabi/jcabi-aether#37]
I experience the same problem as described at http://stackoverflow.com/questions/24925239/jcabi-aether-basic-example-doesnt-work

I use Java 1.7.

The errors mentioned in Eclipse:
Description	Resource	Path	Location	Type
The project was not built since its build path is incomplete. Cannot find the class file for org.apache.maven.project.MavenProject. Fix the build path then try building this project	solution-inspector		Unknown	Java Problem
The type org.apache.maven.project.MavenProject cannot be resolved. It is indirectly referenced from required .class files	MavenPomFinder.java	/myproject/src/main/java/mypackage	line 1	Java Problem

The remark was to create an issue, and afaiks no issue has been made, hence I created this issue.

Best regards,
Herbert

**Comment by walknwind** [comment]
I believe you need to add a dependency to this in your project's POM:
```
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-core</artifactId>
			<version>3.0.5</version>
		</dependency>
```

Here is a pom.xml that worked for me:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.me</groupId>
	<artifactId>my-jcabi-aether</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>my-jcabi-aether</name>
	<description>Test of jcabi-aether</description>

	<dependencies>
		<dependency>
			<groupId>com.jcabi</groupId>
			<artifactId>jcabi-aether</artifactId>
			<version>0.10.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-core</artifactId>
			<version>3.0.5</version>
		</dependency>
	</dependencies>
</project>
```

**Comment by yegor256** [comment]
@walknwind thanks!

**Comment by quartelh** [comment]
@walknwind I will give it a try.

**Comment by quartelh** [comment]
I close this issue since @walknwind mentioned it worked. 
I saw that the example is removed from the page so that does not need to be updated.

@yegor256 perhaps you want to comment on http://stackoverflow.com/questions/24925239/jcabi-aether-basic-example-doesnt-work ? I cannot judge if this solution is also solving that issue
