### ISSUE TITLE
Aether.java:87-89: This class should be @Immutable,...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aether#39]
Puzzle `20-271b1ced` in `src/main/java/com/jcabi/aether/Aether.java:87-89` has to be resolved: This class should be @Immutable, but Proxy and Authentication parameters of Repository are not immutable. Let's create a new classes to encapsulate all necessary properties from them.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@wentwog you're working with this issue for 7 days already. as a reminder, don't forget to remove the `@todo` puzzle from the source code. added -30 to your rating, now it is equal to [+5](http://www.netbout.com/b/35104?open=rating)

**Comment by wentwog** [comment]
@dmarkov I was reading about 10 days deadline in our work model description, I must have missed something. Can you please tell where I can read about the rating system and the deadlines applied ?

**Comment by wentwog** [comment]
@dmarkov and can you please assign the task to someone else, since I feel I don't have time available to meet the deadline.

**Comment by dmarkov** [comment]
> @dmarkov and can you please assign the task to someone else, since I feel I don't have time available to meet the deadline.

@wentwog I'll ask somebody else to pick this up

**Comment by yegor256** [comment]
@wentwog create an account at www.netbout.com and I'll give you access to your rating stats

**Comment by wentwog** [comment]
@yegor256 done, my alias is @wentwog

**Comment by yegor256** [comment]
@wentwog now you should have access here: http://www.netbout.com/b/35104

**Comment by wentwog** [comment]
@yegor256 thanks!
Can you also clarify about the deadlines?:
there two deadlines:
1) 8 days. If haven't finished, even if working on the task now, you get minus in the rating? 
How much? Mine were -5,-5,-30 - so, different.
2) 10 or 14 days? - after that time task can be withdrawn from you.

**Comment by yegor256** [comment]
@wentwog If you keep a task longer than 10 days, you get -30 points (if task budget is 30 minutes). If you fail to complete it in 14 days, you get -60 points. We may change the rules in the future, they are still experimental, but that's what we have now

**Comment by dmarkov** [comment]
@oruam85 it's yours, please go ahead

**Comment by oruam85** [comment]
@dmarkov the PR is https://github.com/jcabi/jcabi-aether/pull/46

**Comment by krzyk** [comment]
@dmarkov give us more time here,  please

**Comment by dmarkov** [comment]
> @dmarkov give us more time here,  please

@krzyk right, take your time and thanks for informing

**Comment by oruam85** [comment]
@dmarkov The PR was merged. Please close this bug

**Comment by oruam85** [comment]
@dmarkov The PR was merged. Please close this bug

**Comment by oruam85** [comment]
@dmarkov The PR was merged. Please close this bug too.

**Comment by oruam85** [comment]
@dmarkov The PR was merged. Please close this bug too.

**Comment by dmarkov** [comment]
Closing, thanks all

**Comment by dmarkov** [comment]
@oruam85 I added **30 mins** to your account, many thanks for working with the project!. added +30 to your rating, now it is equal to +210
