### ISSUE TITLE
MavenClasspathTest.java:101-101: Add handling of broken dependencies...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aether#40]
Puzzle `28-40ea2a55` in `src/test/java/com/jcabi/aether/MavenClasspathTest.java:101-101` has to be resolved: Add handling of broken dependencies in toString.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by alevohin** [comment]
@dmarkov source code from master doesn't pass qulice check, is it normal?
Example from log:
[INFO] --- qulice-maven-plugin:0.10:check (jcabi-check) @ jcabi-aether ---
[INFO] LICENSE found: file:C:/develop/odesk/jcabi-aether/LICENSE.txt
[ERROR] \src\aws-it\aether-test\client\pom.xml[101]: Lines in file should end with Unix-like end of line (RegexpMultilineCheck)
[ERROR] \src\aws-it\aether-test\invoker.properties[1]: Lines in file should end with Unix-like end of line (RegexpMultilineCheck)
[ERROR] \src\aws-it\aether-test\plugin\pom.xml[90]: Lines in file should end with Unix-like end of line (RegexpMultilineCheck)
[ERROR] \src\aws-it\aether-test\plugin\src\main\java\com\jcabi\aether\plugin\package-info.java[1]: Missing a header - not enough lines in file. (HeaderCheck)
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:22 min
[INFO] Finished at: 2015-01-01T11:13:38+04:00
[INFO] Final Memory: 30M/74M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.10:check (jcabi-check) on project jcabi-aether: Failure: 272 Checkstyle violations (see log above) -> [Help 1]

**Comment by yegor256** [comment]
@alevohin No, it's not. Every time you see an issue, create a new ticket

**Comment by alevohin** [comment]
@dmarkov PR #42 merged to master. Please check and close issue.

**Comment by dmarkov** [comment]
Thanks, closing it now.

**Comment by dmarkov** [comment]
@alevohin **30 mins** was added to your account, many thanks for your contribution!

+30 to your rating, your total score is [+165](http://www.netbout.com/b/35105?open=rating)

**Comment by qxo** [comment]
I can not use  this Aether on Maven 3.1, so I have to switch aether library to http://www.eclipse.org/aether/

https://github.com/qxo/jcabi-aether/commit/6317fd43acb41f6662f2934ed3615543ab4fc0d6
