### ISSUE TITLE
The method canEqual is undefined in the MavenClasspath class

### ISSUE THREAD

**Issue by oruam85** [jcabi/jcabi-aether#45]
The test comparesToAnotherClasspath in MavenClasspathTest class and the test comparesToAnotherClasspath in ClasspathTest class have a MatcherAssert using the method canEqual of the MavenClasspath class, but this method not exist.

**Comment by yegor256** [comment]
@oruam85 I'm not sure I follow... how can I reproduce this issue?

**Comment by oruam85** [comment]
@yegor256 look the test comparesToAnotherClasspath in MavenClasspathTest class
```
@Test
    public void comparesToAnotherClasspath() throws Exception {
        final Dependency dep = new Dependency();
        dep.setGroupId("org.apache.commons");
        dep.setArtifactId("commons-lang3-absent");
        dep.setVersion("3.0");
        dep.setScope(JavaScopes.COMPILE);
        final Classpath classpath = new Classpath(
            this.project(dep), this.temp.newFolder(), JavaScopes.TEST
        );
        MatcherAssert.assertThat(classpath, Matchers.equalTo(classpath));
        MatcherAssert.assertThat(
            classpath.canEqual(classpath),
            Matchers.is(true)
        );
    }
```

The line `  classpath.canEqual(classpath) ` does not compile because the method canEqual does not exist

**Comment by oruam85** [comment]
The same problem in the other test comparesToAnotherClasspath in ClasspathTest class

**Comment by yegor256** [comment]
@oruam85 you can't compile the project with `mvn clean compile`??

**Comment by oruam85** [comment]
@yegor256 mvn clean compile build sucess and mvn test too. But in Eclipse, the tests shows the line red because with this message: "The method canEqual(Classpath) is undefined for the type Classpath"

**Comment by yegor256** [comment]
@oruam85 so it's not a bug, it's something wrong with Eclipse. when you report a bug, always remember that you should explain how such a problem can be reproduced.
