### ISSUE TITLE
Wrong management of dependencies duplicated in multiple versions

### ISSUE THREAD

**Issue by kjezek** [jcabi/jcabi-aether#48]
If a dependency tree contains artefacts duplicated in various versions, Maven uses only one. Jcabi-aether returns all of them instead. 

It seem that the root of this problem is in the Classpath class:

This code:

                    final Artifact newer = Classpath.newer(child, found);
                    if (newer.equals(child)) {
                        artifacts.remove(found);
                        artifacts.add(newer);
                    }

contains a condition that is true only when the newer object is a current child. But what if the opossite holds? The current (older) child is added to the "artefacts" list, which already contains the newer artefact. The result is that I have two artefacts differing only in their versions in the list.

I am not sure if the supposed algorithm is correct either. Does Maven really selects a newer version?

**Comment by yegor256** [comment]
@kjezek yes, Maven always gets the newest version if there are duplicates

**Comment by kjezek** [comment]
@yegor256 thanks for extending my knowledge :)

However, the condition is still wrong. If there is already a newer version in the list, an older artefact is also added, which is wrong, right?  Perhaps there should be an "else" branch replacing the "newer" by the "found"

**Comment by yegor256** [comment]
@kjezek you're right, it's a bug, thanks for reporting! we'll take care of it soon

**Comment by dmarkov** [comment]
@cyberone please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have. The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by cyberone** [comment]
@dmarkov assign this task somebody else please

**Comment by dmarkov** [comment]
> @dmarkov assign this task somebody else please

@cyberone right, I will find someone else, no problem

**Comment by dmarkov** [comment]
@maurezen the task is yours

**Comment by maurezen** [comment]
@dmarkov @kjezek created a pull request #52

**Comment by maurezen** [comment]
@kjezek fix merged to master. Please close the issue if it's solved.

**Comment by maurezen** [comment]
@kjezek ping. 

@yegor256 what do we do if the reporter doesn't appear here?

**Comment by dmarkov** [comment]
@maurezen I added **30 mins** to your account, many thanks for working with the project!. +30 added to your rating, current score is: [+1125](http://www.netbout.com/b/35102?open=rating)
