### ISSUE TITLE
"Aether" links to a non existing page

### ISSUE THREAD

**Issue by adko-pl** [jcabi/jcabi-aether#54]
The "Aeather" link on 

- http://aether.jcabi.com/ 
- and  https://github.com/jcabi/jcabi-aether

links to https://docs.sonatype.org/display/AETHER/Home which no longer exists (404).

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@adko-pl fixed in 3f5ff04 thanks!
