### ISSUE TITLE
Can't get Authentication to work

### ISSUE THREAD

**Issue by quartelh** [jcabi/jcabi-aether#56]
Hi, I do not think it is a bug, but I do not seem to get Authentication added to the RemoteRepository. jcabi Aether writes out '... from ["nexus (http://myserver/nexus/content/groups/public, releases+snapshots) without authentication"] into ...'

my code:

``` java
    public static void main(String[] args)
            throws DependencyResolutionException, IOException {
        File local = new File("c:/temp/local-repository");
        RemoteRepository nexus = new RemoteRepository("nexus", "default", "http://myserver/nexus/");

        Authentication auth = new Authentication("myuser", "mypassword");
        nexus.setAuthentication(auth);
        Collection<RemoteRepository> remotes = Arrays.asList(nexus);
        Collection<Artifact> deps = new Aether(remotes, local).resolve(
                new DefaultArtifact("junit", "junit-dep", "", "pom", "4.10"),
                "runtime");

        for (Artifact art : deps) {
            File theFile = art.getFile();
            String theContent = FileUtils.readFileToString(theFile);
            System.out.println(theContent);
        }
    }
```

How do I correctly set authentication to the remoteRepository? For some reason Aether cannot find it, hence it writes out 'without authentication'..

See line 292 in http://aether.jcabi.com/xref/com/jcabi/aether/Aether.html

**Comment by quartelh** [comment]
I also tried with ..."mypassword".toCharArray()...

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@quartelh sorry for the delay. do you still have this problem? looks like something is wrong with your code..

**Comment by quartelh** [comment]
Hi, 
I have abandoned using jcabi, since I could not get it to work. 
Could also be a dependency on a lib that does not seems obvious, but I was unable to pinpoint it. 
The use case is connecting to a repository that requires authentication and is behind a proxy (also with authentication), so I do not know how easy it is to reproduce this. 


Groeten,Herbert
Verzonden vanaf Samsung Mobile.

-------- Oorspronkelijk bericht --------
Van: Yegor Bugayenko <notifications@github.com> 
Datum: 14-07-2015  02:19  (GMT+01:00) 
Aan: jcabi/jcabi-aether <jcabi-aether@noreply.github.com> 
Cc: Herbert Quartel <herbert@quartel.net> 
Onderwerp: Re: [jcabi-aether] Can't get Authentication to work (#56) 

@quartelh sorry for the delay. do you still have this problem? looks like something is wrong with your code..

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-aether#56` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
