### ISSUE TITLE
Estimate project size

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aether#60]
There is no estimate in the project yet. We have to create one as explained [here](https://github.com/teamed/est)

**Comment by dmarkov** [comment]
@super132 it's your task, go ahead

**Comment by super132** [comment]
@dmarkov PR #64 fixed this issue. Would you please close this ticket? Thanks.

**Comment by super132** [comment]
@dmarkov , could you please close this ticket? Thanks.

**Comment by yegor256** [comment]
@rultor deploy

**Comment by super132** [comment]
@dmarkov it has been 5 days since PR is merged. Would you please close it?

**Comment by super132** [comment]
@dmarkov The PR has been merged for a week and this ticket is still not closed. Would you please close it?

**Comment by dmarkov** [comment]
@super132 I added **30 mins** to your account, many thanks for working with the project! The completion time here was AP-9WV79674JX7522642.. +30 added to your rating, at the moment it is: [+361](http://www.netbout.com/b/35282?open=rating)

**Comment by dmarkov** [comment]
@yegor256 The task is done, thanks all, I am closing it
