### ISSUE TITLE
Aether.java:94-97: Create an integration test for...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aether#61]
Puzzle `11-2b91e5db` in `src/main/java/com/jcabi/aether/Aether.java:94-97` has to be resolved: Create an integration test for reading proxy information from maven settings.xml file that will mock an HTTP server using jcabi-http, provide a maven configuration file with proxy settings and verify the expected HTTP requests have been sent to the mocked server.... The puzzle was created by Adam Siemion on 8-Mar-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@yamstranger it's in your hands now, please proceed

**Comment by YamStranger** [comment]
@dmarkov I need more time here

**Comment by dmarkov** [comment]
> @dmarkov I need more time here

@yamstranger OK, take your time

**Comment by YamStranger** [comment]
@dmarkov I cant find any way to solve it even in other projects. Please assign to developer who know how do it.

**Comment by dmarkov** [comment]
> @dmarkov I cant find any way to solve it even in other projects. Please assign to developer who know how do it. 

@yamstranger 30 points was deducted from your rating

**Comment by dmarkov** [comment]
> @dmarkov I cant find any way to solve it even in other projects. Please assign to developer who know how do it. 

@yamstranger I will ask somebody else to pick this up

**Comment by dmarkov** [comment]
@shelan the task is for you now, follow [these guidelines](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Don't hesitate to ask any technical questions right here... The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by shelan** [comment]
I have created an PR here.  #68

**Comment by dmarkov** [comment]
> @dmarkov I have created a PR here.  #68

@shelan OK thanks

**Comment by shelan** [comment]
@dmarkov need more time

**Comment by dmarkov** [comment]
> @dmarkov need more time

@shelan take your time, I am aware that we're waiting here

**Comment by shelan** [comment]
@dmarkov waiting for #68 to be merged.

**Comment by dmarkov** [comment]
> @dmarkov waiting for #68 to be merged.

@shelan #68 is a pull request, we can't call it an impediment

**Comment by dmarkov** [comment]
@yegor256 Done, thanks all, closing..

**Comment by dmarkov** [comment]
@shelan I just added **30 mins** to your account, many thanks for your contribution (112014354).. 10605 hours and 54 mins spent here; +30 to your rating, your total score is [+30](http://www.netbout.com/b/35659?open=rating)
