### ISSUE TITLE
Cannot figure out how to make jcabi-aether play well with maven 3.3.3 plugin development.

### ISSUE THREAD

**Issue by mykelalvis** [jcabi/jcabi-aether#66]
The latest (as of now) version of Maven is 3.3.3.  To use the features of that version required maven-core-3.3.3, which depends on maven-aether-provider-3.3.3 which depends directly on org.eclipse.aether:aether-api:1.0.2.v20150114.

During development of a Maven plugin for 3.3.3, I have been unable to adjust dependencies (within my relatively set boundaries around maven 3.3.3) to make `jcabi-aether` use eclipse dependencies.  #4 indicates that this was solved, but I don't seem to be able to locate documentation that describes how to utilize it.  Per [the latest blob](https://github.com/jcabi/jcabi-aether/blob/master/pom.xml#L109-L144) this appears to still be locked to sonatype's aether implementation, which seems to produce a load-time conflict with the later versions of eclipse's aether.

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by dmarkov** [comment]
@krzyk it's your task now, go ahead

**Comment by dmarkov** [comment]
@krzyk you're holding this task for 15 days already; -30 added to your rating, current score is: [+3238](http://www.netbout.com/b/35035?open=rating)

**Comment by krzyk** [comment]
@dmarkov please assign someone else

**Comment by dmarkov** [comment]
> @dmarkov please assign someone else 

@krzyk -30 points to your rating :(

**Comment by dmarkov** [comment]
> @dmarkov please assign someone else 

@krzyk got it, someone else will be assigned soon

**Comment by dmarkov** [comment]
@piddubnyi please help, the task is yours

**Comment by dmarkov** [comment]
@piddubnyi the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck. -30 to your rating, your total score is [-60](http://www.netbout.com/b/35966?open=rating)

**Comment by dmarkov** [comment]
@piddubnyi you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

-60 to your rating, your total score is [-180](http://www.netbout.com/b/35966?open=rating)

**Comment by mykelalvis** [comment]
This is very old, and while it might be important to some, it's definitely no longer important to me.  I'm going to close.  If that turns out to be inappropriate, someone should feel free to reopen.

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-aether#66` is not assigned, can't get performer
