### ISSUE TITLE
Pom file parent as a dependency

### ISSUE THREAD

**Issue by lmprice** [jcabi/jcabi-aether#70]
Hey,

I'm currently writing a small application to mirror dependencies from maven central into a local repository that will be pushed to another server and be used offline for more "official" builds. One thing I've noticed is that some dependencies will have a pom file that references another pom, called the parent. Aether will retrieve these files, but they aren't treated as true dependencies. Therefore, if I attempt to use the offline repository I've created with just the list of artifacts that Aether reports on the resolve, it will be incomplete.

Is there some functionality I'm missing with regard to these? It'd be great if these were treated as true dependencies. It's looking like I'm going to have to parse each of the retrieved pom files and read the xml to determine if there is a parent I should add as an additional dependency. I'm much more familiar with ant+ivy, so it's possible I'm missing something obvious.

Thanks,

Michael

<hr id='w'>

**Comment by dmarkov** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@lmprice good question... I don't have an answer. let's register this bug and maybe someone from our team can fix it.

**Comment by dmarkov** [comment]
@gmandnepr could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here; Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by gmandnepr** [comment]
@yegor256 Parent is not a dependency in any of org.sonatype.aether.util.artifact.JavaScopes. So I believe it should not be accessible via current Aether#resolve() or RootArtifact#children().

I could add RootArtifact#parent(). This method will have to read pom file from repository as parent information is not present in Artifact.

https://dev.eclipse.org/mhonarc/lists/aether-users/msg00115.html
https://dev.eclipse.org/mhonarc/lists/aether-users/msg00052.html
http://www.programcreek.com/java-api-examples/index.php?api=org.sonatype.aether.util.artifact.DefaultArtifact (example 14)

**Comment by gmandnepr** [comment]
@dmarkov I can't wait more for response on previous comment. Please re-assign this task on someone else

**Comment by dmarkov** [comment]
> @dmarkov I can't wait more for response on previous comment. Please re-assign this task on someone else

@gmandnepr 30 points was deducted from your rating

**Comment by dmarkov** [comment]
> @dmarkov I can't wait more for response on previous comment. Please re-assign this task on someone else

@gmandnepr I will try to find someone else

**Comment by dmarkov** [comment]
@piddubnyi the task is yours

**Comment by piddubnyi** [comment]
@dmarkov Assign to someone else please.

**Comment by dmarkov** [comment]
> @dmarkov Assign to someone else please.

@piddubnyi -30 points to your rating :(

**Comment by dmarkov** [comment]
> @dmarkov Assign to someone else please.

@piddubnyi got it, someone else will be assigned soon

**Comment by dmarkov** [comment]
@amihaiemil the task is yours

**Comment by amihaiemil** [comment]
@dmarkov Please assign to someone else.

**Comment by dmarkov** [comment]
> @dmarkov Please assign to someone else.
> 

@amihaiemil 30 points deducted from your rating

**Comment by dmarkov** [comment]
> @dmarkov Please assign to someone else.
> 

@amihaiemil OK, I will try to assign someone else

**Comment by dmarkov** [comment]
@prondzyn the task is yours, go ahead

**Comment by prondzyn** [comment]
@dmarkov PR #91 prepared

**Comment by dmarkov** [comment]
> @dmarkov PR #91 prepared

@prondzyn thank you!

**Comment by prondzyn** [comment]
@dmarkov I need more time waiting on @yegor256 's confirmation.

**Comment by dmarkov** [comment]
> @dmarkov I need more time waiting on @yegor256 's confirmation.

@prondzyn of course, take your time

**Comment by prondzyn** [comment]
@dmarkov I need more time. Still waiting on @yegor256.

**Comment by dmarkov** [comment]
> @dmarkov I need more time. Still waiting on @yegor256.

@prondzyn sure, take your time, I know about this pause

**Comment by prondzyn** [comment]
@dmarkov I need more time. Still waiting on @yegor256.

**Comment by dmarkov** [comment]
> @dmarkov I need more time. Still waiting on @yegor256.

@prondzyn sure, take your time, I know about this pause

**Comment by prondzyn** [comment]
@dmarkov I need more time. Still waiting on @yegor256.

**Comment by amihaiemil** [comment]
@prondzyn just as a note, as far as I know, it's enough to let the pm know just once - I asked more time once in August and that's it, still waiting ^^

**Comment by prondzyn** [comment]
@amihaiemil thanks for letting me know. No one had told me about this before and I didn't find any info about it ;)

**Comment by dmarkov** [comment]
> @dmarkov I need more time. Still waiting on @yegor256.

@prondzyn yeah, I know, take your time

**Comment by prondzyn** [comment]
@dmarkov I need more time. Still waiting on @yegor256.

**Comment by dmarkov** [comment]
> @dmarkov I need more time. Still waiting on @yegor256.

@prondzyn take your time, I am aware that we're waiting here

**Comment by prondzyn** [comment]
@lmprice PR #91 merged. Please close this issue.

**Comment by dmarkov** [comment]
@lmprice the code made here contains a puzzle `70-7b24e628`/#95, which will be resolved soon

**Comment by prondzyn** [comment]
@lmprice can you close this issue, please?

**Comment by lmprice** [comment]
@prondzyn Much appreciated.

**Comment by dmarkov** [comment]
@prondzyn paid, thanks, added **30 mins** to your account, payment `AP-21A42504P7427034U`, 1483 hours and 39 mins was spent

+30 added to your rating, current score is: [+150](http://www.netbout.com/b/35715?open=rating)
