### ISSUE TITLE
Aether.java:97-97: Fix NullPointerExceptions in CL build...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aether#78]
Puzzle `69-fd6545e6` in `src/main/java/com/jcabi/aether/Aether.java:97-97` has to be resolved: Fix NullPointerExceptions in CL build for Open JDK6.... The puzzle was created by Igor Piddubnyi on 25-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by dmarkov** [comment]
@amihaiemil could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by amihaiemil** [comment]
@dmarkov I created PR #80 for this issue.

**Comment by dmarkov** [comment]
> @dmarkov I created PR #80 for this issue.

@amihaiemil thank you

**Comment by amihaiemil** [comment]
@dmarkov The PR #80 for this has been merged and closed. You can close this ticket.

**Comment by amihaiemil** [comment]
@dmarkov Don't forget to close this ticket. Thanks.

**Comment by amihaiemil** [comment]
@dmarkov ping. Please close this.

**Comment by amihaiemil** [comment]
@dmarkov ping

**Comment by dmarkov** [comment]
> @dmarkov The PR #80 for this has been merged and closed. You can close this ticket.

@amihaiemil OK

**Comment by dmarkov** [comment]
@amihaiemil check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

do not forget that you should remove the `@todo` puzzle from the source code

-30 added to your rating, at the moment it is: [-30](http://www.netbout.com/b/36402?open=rating)

**Comment by amihaiemil** [comment]
@dmarkov I created PR #81 in which I removed the puzzle... I honestly forgot about it all along the way. Please find someone to merge it asap. Thanks.

**Comment by amihaiemil** [comment]
@dmarkov I need more time

**Comment by amihaiemil** [comment]
@dmarkov we have to wait for issue #82 to be solved

**Comment by dmarkov** [comment]
> @dmarkov Don't forget to close this ticket. Thanks. 
> 

@amihaiemil I never forget

**Comment by dmarkov** [comment]
> @dmarkov ping. Please close this.
> 

@amihaiemil no need to ping me, I know when to close tickets

**Comment by dmarkov** [comment]
> @dmarkov ping 

@amihaiemil instead of pinging me, try not to forget to remove puzzles :)

**Comment by dmarkov** [comment]
> @dmarkov I need more time

@amihaiemil of course, take your time

**Comment by amihaiemil** [comment]
@dmarkov My apologies... don't forget we're waiting here for issue #82 here. Thanks

**Comment by dmarkov** [comment]
> @dmarkov we have to wait for issue #82 to be solved

@amihaiemil sure, we'll wait for #82

**Comment by dmarkov** [comment]
@yegor256 FYI, issue #82 is already closed, and we were waiting for it..

**Comment by amihaiemil** [comment]
@dmarkov PR #81 has been merged and closed. Please close this ticket. Thanks.

**Comment by amihaiemil** [comment]
@dmarkov It says that I removed my assignment. I only left a comment. I don't know what happenned.

**Comment by amihaiemil** [comment]
@dmarkov please don't forget to close this ticket. Thanks.

**Comment by amihaiemil** [comment]
@yegor256 Same here (as in https://github.com/jcabi/jcabi-email/issues/36),, my assignment was removed when I left a comment.

**Comment by dmarkov** [comment]
> @dmarkov PR #81 has been merged and closed. Please close this ticket. Thanks.

@amihaiemil OK

**Comment by dmarkov** [comment]
@yegor256 The issue is closed

**Comment by dmarkov** [comment]
@amihaiemil Thank you, I have added **30 mins** to your account in payment/transaction "`AP-5U600179DS555602E`", time consumed: 190 hours and 49 mins. +30 added to your rating, at the moment it is: [+360](http://www.netbout.com/b/36402?open=rating)
