### ISSUE TITLE
Aether.java:98-98: Fix UnsupportedClassVersionError in CL build...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aether#79]
Puzzle `69-46002db1` in `src/main/java/com/jcabi/aether/Aether.java:98-98` has to be resolved: Fix UnsupportedClassVersionError in CL build for Open JDK6.... The puzzle was created by Igor Piddubnyi on 27-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by dmarkov** [comment]
@nikoladespotoski the task is yours please proceed

**Comment by dmarkov** [comment]
@nikoladespotoski you're holding this task for 15 days already. do not forget that the ticket will be closed once the `@todo` puzzle is removed from the code, in master branch. -30 added to your rating, current score is: [+155](http://www.netbout.com/b/36438?open=rating)

**Comment by NikolaDespotoski** [comment]
@dmarkov assign someone else

**Comment by dmarkov** [comment]
> @dmarkov assign someone else

@nikoladespotoski got it, someone else will be assigned soon

**Comment by dmarkov** [comment]
@yegor256 Thanks all, I am closing
