### ISSUE TITLE
Aether.java:97-100: Clean unnecessary docker setup (src/docler/Dockerfile),...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aether#84]
Puzzle `82-ba434d45` in `src/main/java/com/jcabi/aether/Aether.java:97-100` has to be resolved: Clean unnecessary docker setup (src/docler/Dockerfile), make the configuration minimal. Set versions to the used packages (e.g. lock java version instead of default jdk). After changes, the file needs to be uploaded to Dockerhub and be built there.... The puzzle was created by Mihai Andronache on 7-Apr-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by dmarkov** [comment]
@prondzyn it's your task, go ahead

**Comment by prondzyn** [comment]
@dmarkov please find someone else

**Comment by dmarkov** [comment]
> @dmarkov please find someone else

@prondzyn I deducted 30 points from your rating

**Comment by dmarkov** [comment]
> @dmarkov please find someone else

@prondzyn got it, someone else will be assigned soon

**Comment by dmarkov** [comment]
@amihaiemil please help, the task is yours

**Comment by amihaiemil** [comment]
@dmarkov PR #90  is for this

**Comment by dmarkov** [comment]
> @dmarkov PR #90  is for this

@amihaiemil thank you

**Comment by amihaiemil** [comment]
@dmarkov I need more time

**Comment by dmarkov** [comment]
> @dmarkov I need more time

@amihaiemil sure, thanks for telling me, take your time

**Comment by amihaiemil** [comment]
@dmarkov close this ticket please

**Comment by amihaiemil** [comment]
@dmarkov ping

**Comment by dmarkov** [comment]
@yegor256 The task is done, thanks all, I am closing it

**Comment by dmarkov** [comment]
@amihaiemil **30 mins** added to your account (payment number `AP-67N467683P411290K`), many thanks for your contribution! 790 hours and 54 mins spent here.; +30 to your rating, your total score is [+564](http://www.netbout.com/b/36402?open=rating)
