### ISSUE TITLE
Constructors for classpath of Maven Project should accept var args

### ISSUE THREAD

**Issue by simonjenga** [jcabi/jcabi-aether#88]
The following constructors should be refactored in order to accept variable arguments. At the moment they can only accept one String argument e.g. "runtime" or "compile"

```java
/**
 * Public ctor.
 * @param prj The Maven project
 * @param repo Local repository location (directory path)
 * @param scp The scope to use, e.g. "runtime" or "compile"
 */
public Classpath(final MavenProject prj, final File repo,
	final String scp) {
	this(prj, repo, Arrays.asList(scp));
}

/**
 * Public ctor.
 * @param bldr Dependency graph builder.
 * @param sess Maven session.
 * @param scp The scope to use, e.g. "runtime" or "compile"
 */
public MavenClasspath(final DependencyGraphBuilder bldr,
	final MavenSession sess, final String scp) {
	this(bldr, sess, Arrays.asList(scp));
}
```

Once the refactoring is done, it will be possible to pass more that one argument for the scope to use e.g: ``` "runtime", "compile", "test", "system", "provided" ```

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by dmarkov** [comment]
@simonjenga thank you for reporting this, I added 15 mins to your acc, transaction `90841318`

**Comment by dmarkov** [comment]
@amihaiemil the task is yours

**Comment by amihaiemil** [comment]
Pr #89 is for this issue

**Comment by amihaiemil** [comment]
@simonjenga The PR was merged and closed. Can you close this issue? :D

**Comment by amihaiemil** [comment]
@simonjenga ping

**Comment by amihaiemil** [comment]
@simonjenga please don't forget about this! Thanks

**Comment by simonjenga** [comment]
:ok:
Try to relax! :relaxed:

**Comment by amihaiemil** [comment]
@simonjenga thanks :D

**Comment by amihaiemil** [comment]
@dmarkov This issue is now closed.

**Comment by dmarkov** [comment]
@amihaiemil Many thanks! **30 mins** were added to your account in Transaction ID `AP-8TW75534JU567725X` (task took 219 hours and 31 mins)

added +30 to your rating, now it is equal to [+195](http://www.netbout.com/b/36402?open=rating)

**Comment by dmarkov** [comment]
> @dmarkov This issue is now closed.

@amihaiemil OK thanks

**Comment by dmarkov** [comment]
> @dmarkov ping

@amihaiemil we're good here
